version: 1
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(pathname)s:%(lineno)s'

handlers:
  consol:
    class: loggind.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    file: log/project_logs.log
    maxBytes: 10485760
    backupCount: 5

  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 5242880  # 5 MB
    buckupCount: 4

loggers: 
  "":
    level: INFO
    handlers: [consol, file]
    propagate: no 
  src.api:
    level: DEBUG
    handlers: [consol, file]
    propagate: no


